# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: j.dymond@turing.ac.uk
full_name: Jack Dymond
license: MIT
min_python_version: '3.10'
org: j-dymond
project_name: ARC-TIGERS
project_short_description: Testing Imbalanced cateGory classifiERS
python_name: arc_tigers
typing: loose
url: https://github.com/alan-turing-institute/ARC-TIGERS
