seed: 42
num_train_epochs: 3
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
warmup_ratio: 0.1
weight_decay: 0.01
save_total_limit: 1
eval_strategy: epoch
save_strategy: epoch
load_best_model_at_end : True
learning_rate: 1.0e-5
