seed: 42
num_train_epochs: 1
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 2
warmup_ratio: 0.1
weight_decay: 0.01
save_total_limit: 1
eval_strategy: steps
save_strategy: steps
eval_steps: 400
save_steps: 400
load_best_model_at_end : True
learning_rate: 1.0e-5
fp16: True
dataloader_num_workers: 8
dataloader_prefetch_factor: 1
