model_config: distilbert
data_config: reddit_football
exp_name: football_distilbert
random_seed: 42
train_kwargs:
  num_train_epochs: 3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  warmup_steps: 500
  weight_decay: 0.01
  save_total_limit: 3
  eval_strategy: epoch
  save_strategy: epoch
  load_best_model_at_end : True
