model_config: distilbert
data_config: reddit_sport_1_in_10
exp_name: sport_distilbert_imb_train_1_in_10
random_seed: 65
train_kwargs:
  num_train_epochs: 3
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  warmup_steps: 500
  weight_decay: 0.01
  save_total_limit: 3
  eval_strategy: epoch
  save_strategy: epoch
  load_best_model_at_end : True
